version: "3.9"

services:
    backend:
        build:
            context: .
            dockerfile: docker/django/Dockerfile
        container_name: project
        env_file:
            - .env
        volumes:
            - ./project/:/code/
        ports:
            - "8000:8000"
        depends_on:
            - redis
        command: python manage.py runserver 0.0.0.0:8000

    redis:
        image: redis:7.0
        container_name: redis
        ports:
            - "6379:6379"
